# Generated by Django 6.0.1 on 2026-04-10 11:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0002_farmer_district_farmer_state_farmer_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('crop_type', models.CharField(choices=[('WHEAT', 'Wheat (गेहूं)'), ('RICE', 'Rice (चावल)'), ('TOMATO', 'Tomato (टमाटर)'), ('POTATO', 'Potato (आलू)'), ('ONION', 'Onion (प्याज)'), ('MANGO', 'Mango (आम)'), ('SUGARCANE', 'Sugarcane (गन्ना)')], max_length=20)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('harvest_date', models.DateField()),
                ('quality_grade', models.CharField(blank=True, choices=[('A', 'Grade A - Premium'), ('B', 'Grade B - Good'), ('C', 'Grade C - Standard')], max_length=10, null=True)),
                ('current_status', models.CharField(choices=[('HARVESTED', 'Harvested on Farm'), ('COLLECTION_CENTER', 'At Collection Center'), ('IN_TRANSIT', 'In Transit'), ('WAREHOUSE', 'At Warehouse'), ('RETAILER', 'Delivered to Retailer'), ('COMPLETED', 'Completed')], default='HARVESTED', max_length=30)),
                ('qr_code_url', models.URLField(blank=True, null=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_at_centre', models.DateTimeField(blank=True, null=True)),
                ('expected_at_warehouse', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='communication.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Batch_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('HARVESTED', 'Harvested on Farm'), ('COLLECTION_CENTER', 'At Collection Center'), ('IN_TRANSIT', 'In Transit'), ('WAREHOUSE', 'At Warehouse'), ('RETAILER', 'Delivered to Retailer'), ('COMPLETED', 'Completed')], max_length=30)),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_by_role', models.CharField(choices=[('FARMER', 'Farmer'), ('COLLECTION_CENTER', 'Collection Center Staff'), ('TRANSPORT', 'Transport Officer'), ('WAREHOUSE', 'Warehouse Manager'), ('RETAILER', 'Retailer')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tracking.crop_batch')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(blank=True, max_length=100)),
                ('farmer_SpeechText', models.TextField(blank=True)),
                ('farmer_AudioURL', models.URLField(blank=True)),
                ('ai_ResponseText', models.TextField(blank=True)),
                ('ai_AudioURL', models.URLField(blank=True)),
                ('extracted_data', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_logs', to='tracking.crop_batch')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_logs', to='communication.farmer')),
            ],
        ),
    ]
